#!/bin/bash
set -eu

typeset -a doc_classes
doc_classes=($(papis list --libraries | cut -d' ' -f 2))

echo "Syncing the following classes: ${doc_classes[@]}"
echo "Committing changes"
parallel "(cd {}; git add '*'; git commit -m 'Auto-bump version at $(date) on $(hostname)') " ::: ${doc_classes[@]}

echo "Pulling changes..."
parallel 'cd {}; git pull &> git.update_tmp' ::: ${doc_classes[@]}

echo "Looking for merge conflicts..."
for class in ${doc_classes[@]}; do
	pushd $class
	if [[ $(grep -ce 'MERGE CONFLICT' git.update_tmp || true) -gt 0 ]]; then
		echo "Merge conflict found for library $class"
		echo "Message was:"
		cat git.update_tmp
		echo "Merge conflict found for library $class"
		echo "Please resolve and commit the conflict."
		echo "Press <Enter> after the merge conflict is resolved"
		read -q 'tmp?'
	fi

	rm git.update_tmp
	popd
done

echo "Updating database... (in background, while pushing)"
parallel 'papis -l {} --cc' ::: ${doc_classes[@]} &

echo "Pushing to repositories..."
parallel 'cd {}; git push' ::: ${doc_classes[@]}

wait
echo "Repositories synced! (${doc_classes[@]})"
