#!/bin/zsh

loads=( $(qhost | tr -s ' ' | cut -f7 -d' ' | grep '\.') )

sum=0
tot=0
nodes_under_ten=0

for l in ${loads[@]}; do
	sum=$((sum + l))
	tot=$((tot + 1))
	if (( l < 0.10 )); then
		nodes_under_ten=$((nodes_under_ten + 1))
	fi
done

echo "Mean load is $((sum / tot))"
echo "$nodes_under_ten nodes under 10% utilization"
